/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'navy': '#0f172a',
        'electric': '#3b82f6',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'background': '#fcf8fa',
        'surface': '#fcf8fa',
        'surface-bright': '#fcf8fa',
        'surface-variant': '#e5e1e3',
        'surface-container': '#f1edef',
        'surface-container-low': '#f6f2f4',
        'surface-container-high': '#ebe7e9',
        'surface-container-highest': '#e5e1e3',
        'on-surface': '#1c1b1d',
        'on-surface-variant': '#47464c',
        'outline': '#78767d',
        'outline-variant': '#c8c5cd',
        'primary': '#00000b',
        'on-primary-container': '#83829b',
        'primary-container': '#1a1a2e',
        'secondary': '#585f6c',
        'on-secondary-container': '#5e6572',
        'secondary-container': '#dce2f3',
        'tertiary': '#695d3c',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#b9aa83',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        display: ['Newsreader', 'serif'],
        body: ['Public Sans', 'sans-serif'],
        label: ['Public Sans', 'sans-serif'],
        sans: ['Public Sans', 'sans-serif'],
        serif: ['Newsreader', 'serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      boxShadow: {
        'soft': '0 2px 8px rgba(0, 0, 0, 0.07)',
        'card': '0 4px 20px rgba(0, 0, 0, 0.06)',
        'glass': '0 8px 32px rgba(0, 0, 0, 0.08)',
      },
    },
  },
  plugins: [],
}
